### ISSUE TITLE
Navigate between screens with Compose: Missing currentScreen parameter

### ISSUE THREAD

**Issue by mattiasjback** [google-developer-training/basic-android-kotlin-compose-training-cupcake#10]
The instructions are lacking description of adding the currentScreen parameter below.
Also the title parameter of the CupCakeScreen enum is missing.

```
@Composable
fun CupcakeAppBar(
    currentScreen: CupcakeScreen,
    canNavigateBack: Boolean,
    navigateUp: () -> Unit,
    modifier: Modifier = Modifier
) {
    TopAppBar(
        title = { Text(stringResource(currentScreen.title)) },
        
       
```

**Comment by hhyeok1026** [comment]
Document 4. Define routes and create a NavHostController should also be updated.

A title is added to the enum class, but there is no explanation.

**Comment by johnshea** [comment]
Hi @hhyeok1026 

Thank you for bringing this item to our attention.

The lesson has been corrected and republished.

Hope you are enjoying the course.

Regards.
