### ISSUE TITLE
Navigate between screens with Compose: Android Basics with Compose

### ISSUE THREAD

**Issue by lixoten** [google-developer-training/basic-android-kotlin-compose-training-cupcake#12]
This Codelab is so buggy, and the instructions do not match the solution step by step, not to mention the instructions are so convoluted it makes it impossible for beginners to follow it, Scrap it.. and try again

**Comment by AlanDerich** [comment]
I concur. I spent most of the time trying to fix an error instead of grasping the message. It seems like they did not test the module before deploying it 😄😄.
