### ISSUE TITLE
Navigate between screens with Compose: Android Basics with Compose

### ISSUE THREAD

**Issue by SergioTellezSanchez** [google-developer-training/basic-android-kotlin-compose-training-cupcake#18]
![image](https://user-images.githubusercontent.com/49140286/202343202-e15d2627-c1ef-4edb-8639-66449b3a75ff.png)

**Comment by osuleymanova** [comment]
Hello @SergioTellezSanchez,

Thanks for reaching out to us. Whatever you are concerned about, it is fixed now:

![Screenshot 2023-01-09 at 11 35 27 AM](https://user-images.githubusercontent.com/86437155/211396144-449f2e2c-0858-4862-94f6-9be6126ef89f.png)
