### ISSUE TITLE
Test the Cupcake app: Android Basics in Compose

### ISSUE THREAD

**Issue by myhency** [google-developer-training/basic-android-kotlin-compose-training-cupcake#19]
7. Add the @Test annotation to the setupCupcakeNavHost() method.

Seems like `@Test` should be changed to `@Before`.

**Comment by osuleymanova** [comment]
@myhency 
Thank you for reaching out to us. The typo is fixed and published:

![Screen Shot 2022-11-18 at 10 20 33 AM](https://user-images.githubusercontent.com/86437155/202820645-757d7005-0ee0-4adb-9261-fca853bf561d.png)
