### ISSUE TITLE
Test the Cupcake app: Android Basics in Compose: onNodeWithStringId is not longer available 

### ISSUE THREAD

**Issue by SergioTellezSanchez** [google-developer-training/basic-android-kotlin-compose-training-cupcake#22]
![image](https://user-images.githubusercontent.com/49140286/202528858-4eacd3f9-3f0e-4f26-bfaa-2de8efe3b663.png)

This worked for me:

    @Test
    fun cupcakeNavHost_clickOneCupcake_navigatesToSelectFlavorScreen() {
        composeTestRule.onNodeWithText(composeTestRule.activity.getString(R.string.one_cupcake))
            .performClick()
        navController.assertCurrentRouteName(CupcakeScreen.Flavor.name)
    }

**Comment by DeanH1990** [comment]
You can still use just the onNodeWithStringId by putting com.example.cupcake before the string id

`composeTestRule.onNodeWithStringId(com.example.cupcake.R.string.one_cupcake)`

This worked for me

**Comment by johnshea** [comment]
Hi @SergioTellezSanchez

Thank you for writing in with this issue.

The lesson is being updated to show the missing import statement. It will be republished in the near future.

Hope you are enjoying the course!

Regards.
