### ISSUE TITLE
Navigate between screens with Compose: Android Basics with Compose

### ISSUE THREAD

**Issue by hassan0599** [google-developer-training/basic-android-kotlin-compose-training-cupcake#24]
Step 5 (Navigate between routes) -> Add button handlers to SummaryScreen -> Sub-step 2

The text should read:
Add another parameter of type `(String, String) -> Unit` and name this one `onSendButtonClicked`.

Instead of:
Add another parameter of type `() -> Unit` and name this one `onSendButtonClicked`.

**Comment by osuleymanova** [comment]
Hello @hassan0599,

Thank you for reaching out to us. The step is updated:

![Screenshot 2023-01-05 at 2 14 09 PM](https://user-images.githubusercontent.com/86437155/210890654-dc0e5780-3a54-4a22-8e9d-cafd9ca9e716.png)
