### ISSUE TITLE
Test the Cupcake app: Android Basics in Compose

### ISSUE THREAD

**Issue by chaberfeld** [google-developer-training/basic-android-kotlin-compose-training-cupcake#25]
The CupcakeOrderScreenTest file, in package androidTest/java, contains a Test function (summaryScreen_verifyContentDisplay) with a minor error. The last call to composeTestRule.onNodeWithText() is missing an Assert statement. Should read:

        composeTestRule.onNodeWithText(
            composeTestRule.activity.getString(
                R.string.subtotal_price,
                fakeOrderUiState.price
            )
        ).assertIsDisplayed()

**Comment by johnshea** [comment]
Hi @chaberfeld 

Thank you for spotting this issue and reporting it.

I have updated the code and the fix will be published in the near future.

Hope you are enjoying the course!

Regards.
