### ISSUE TITLE
Wrong Method Name shown on "Navigate between screens with Compose" (NavHostController)

### ISSUE THREAD

**Issue by MarcelloLins** [google-developer-training/basic-android-kotlin-compose-training-cupcake#28]
Item 1 of [this page](https://developer.android.com/codelabs/basic-android-kotlin-compose-navigation?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-4-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-navigation#6) mentions the following instruction and code:

In the `CupcakeApp` composable, below the `navController` variable, create a variable named `backStackEntry` and call the `currentBackStackEntry()` method of `navController` using the `by` delegate.

```
@Composable
fun CupcakeApp(modifier: Modifier = Modifier, viewModel: OrderViewModel = viewModel()){

    val navController = rememberNavController()

    val backStackEntry by navController.currentBackStackEntryAsState()

    ...
}
```

The instruction says that the method from the `navController` is `currentBackStackEntry()` when it is actually `currentBackStackEntryAsState()`.

The correct text should be:

In the `CupcakeApp` composable, below the `navController` variable, create a variable named `backStackEntry` and call the `currentBackStackEntryAsState()` method of `navController` using the `by` delegate.

**Comment by osuleymanova** [comment]
Hello @MarcelloLins,

Good catch, thanks for for reporting this issue. It is fixed:

![Screenshot 2023-01-09 at 10 37 36 AM](https://user-images.githubusercontent.com/86437155/211383080-ef3a6fac-4785-43f6-b5ee-40ebab162246.png)
