### ISSUE TITLE
Navigate between screens with Compose: Android Basics with Compose

### ISSUE THREAD

**Issue by sandstroms** [google-developer-training/basic-android-kotlin-compose-training-cupcake#3]
In part 6 (Navigate to Another App), there seems to be a typo in the process for setting up a basic intent. In step 2 of this process, it states 
> For a simple piece of text, you can use `"text/plain"`, though other types, such as \<insert examples\>, are available.

It seems like the "\<insert examples\>" text was a reminder to the author(s) of this document to add some examples of other additional data types to be sent with an intent, but it was never replaced.

**Comment by osuleymanova** [comment]
@sandstroms 
Thank you for reaching out to us. The typo is fixed and will be published soon:

![Screen Shot 2022-09-23 at 1 37 48 PM](https://user-images.githubusercontent.com/86437155/192052848-c159a8f9-a7af-464b-8c42-f78be048f6d7.png)
