### ISSUE TITLE
Navigate between screens with Compose: Android Basics with Compose

### ISSUE THREAD

**Issue by Niranjan-Baur** [google-developer-training/basic-android-kotlin-compose-training-cupcake#30]
**Inside the**  
### Add button handlers to SelectOptionScreen
**I am facing an issue on Point Number 3 and 4**

OutlinedButton(modifier = Modifier.weight(1f), **onClick = onCancelButtonClicked**) {
    Text(stringResource(R.string.cancel))
}

above this code snippet onClick has some problem and that should be **onClick = onCancelButtonClicked()** with **opening and closing parenthesis ()**

**point 4**

also for the **onClick = onNextButtonClicked( )**

without the parenthesis, it's not working...

**Comment by wseubert** [comment]
onNext... and onCancel... are variables pointing to a function (I'm still new to Kotlin terminology so this may seem C++ish).  

In OutlinedButton onClick is expecting either a lambda or a pointer to a function so you simply need to make it an assignment like:
onClick = onCancelButtonClicked

**Comment by brendanbdev** [comment]
You need the parentheses when the fun param is inside of curly braces, which the starter code gives you for some reason. So your code probably looks like:

onClick = { onCancelButtonClicked() }

when it can be

onClick = onCancelButtonClicked

That might be your issue. BUT you do need those curly braces for when it is a lambda like onNextButtonClicked in the StartOrderScreen composable, or onSendButtonClicked in the SummaryScreen composable.

I hope this helps.

**Comment by johnshea** [comment]
Hi @Niranjan-Baur 

From the conversation, it appears that an explanation was provided for your issue.

If you are still having problems with the lesson, please do not hesitate to create a new issue with the required information.

Hope you are enjoying the course!

@wseubert @brendanbdev Thank you for helping another student with their issue. It is much appreciated.

Regards.
