### ISSUE TITLE
Navigate between screens with Compose: Android Basics with Compose

### ISSUE THREAD

**Issue by sreedevnair** [google-developer-training/basic-android-kotlin-compose-training-cupcake#31]
**URL of codelab**
[https://developer.android.com/codelabs/basic-android-kotlin-compose-navigation?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-4-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-navigation#6](https://developer.android.com/codelabs/basic-android-kotlin-compose-navigation?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-4-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-navigation#6)

**In which task and step of the codelab can this issue be found?**
One Step 7 | Make the AppBar respond to the navigation

**Describe the problem**
In the 4th point of this step (_4. Inside CupcakeAppBar..._), there is a syntax error in the given code block. We are not calling the _.title_ from the _currentScreen_ parameter.

```
TopAppBar(
   title = { Text(stringResource(currentScreen.)) },
   modifier = modifier,
   navigationIcon = {
       if (canNavigateBack) {
           IconButton(onClick = navigateUp) {
               Icon(
                   imageVector = Icons.Filled.ArrowBack,
                   contentDescription = stringResource(R.string.back_button)
               )
           }
       }
   }
)
```

It should be :

```
TopAppBar(
   title = { Text(stringResource(currentScreen.title)) },
   modifier = modifier,
   navigationIcon = {
       if (canNavigateBack) {
           IconButton(onClick = navigateUp) {
               Icon(
                   imageVector = Icons.Filled.ArrowBack,
                   contentDescription = stringResource(R.string.back_button)
               )
           }
       }
   }
)
```

![image](https://user-images.githubusercontent.com/55118303/213249838-6d122c3c-9bf6-47d4-99f2-bd9b1ade53d3.png)

**Comment by johnshea** [comment]
Hi @sreedevnair 

Thank you for bringing this item to our attention.

All the details you provided really helped. It allowed us to find the issue quickly and address it.

The lesson has been corrected and republished.

Hope you are enjoying the course.

Regards.
