### ISSUE TITLE
Navigate between screens with Compose: Android Basics with Compose Step 5

### ISSUE THREAD

**Issue by AAB999** [google-developer-training/basic-android-kotlin-compose-training-cupcake#32]
On Step 5
![image](https://user-images.githubusercontent.com/122721763/213915295-38a8b553-91b1-47dd-8337-87b91c3fa685.png)

I cannot go furhter then Flavor. 
The "onNextButtonClicked from Flavor to Pickup is not working.

I already copied the whole NavHost from the solution and the issue is still the same.
I cannot find the fault.

![image](https://user-images.githubusercontent.com/122721763/213915484-a99575fa-a3af-4c5b-a6a6-628eae0c0309.png)

Ich already tried to figure out, what happens on the Event with Log.d
On SelectedOptionScreen the onNextButtonClicked is received, but in the Flavor Screen, nothing happens...??? And the Log.d is not carried out at all. 

I can not go to the PickupScreen. I am really confused and dont know, where to look after the Problem anymore...

Since nobody else seems to have this problem....it is probably my own fault (or nobody had tried the navigation at this time of the codlab??)...but I dont know where I coud have made it...

And funny thing is, that i can got to Pickup directly from Start...... Where is the fault here?

![image](https://user-images.githubusercontent.com/122721763/213916308-f842febc-3f52-4aaa-a31b-a76c33c9d463.png)

AND...the "Cancel" Button is not working either...

**Comment by brendanbdev** [comment]
You gotta show more of your code than that, but note that both the Flavor and Pickup routes should both be using the SelectOptionScreen composable, BUT they obviously have their respective arguments for that composable (options, onSelectionChanged) so make sure you don't have the same arguments for both routes' SelectOptionScreen by mistake. I would then verify if your routes are correct. I hope this helps.

**Comment by AAB999** [comment]
> You gotta show more of your code than that, but note that both the Flavor and Pickup routes should both be using the SelectOptionScreen composable, BUT they obviously have their respective arguments for that composable (options, onSelectionChanged) so make sure you don't have the same arguments for both routes' SelectOptionScreen by mistake. I would then verify if your routes are correct. I hope this helps.
> 
> Also the cancel button isn't supposed to work at this point of the tutorial.

Thanks for your concern! But yes, I had that in mind. My Code for the Route in the NavHost is exactly the same, as in the solution but doesn't work. I left it this way and moved on in the pathway... 😊😊

**Comment by AAB999** [comment]
I do not wonder anymore and moved on. ....

**Comment by brendanbdev** [comment]
I know you said you moved on, but I must say that I was wrong, and this is actually very important to know regarding Kotlin syntax... in the SelectOptionScreen composable, make sure you do not have curly braces around the onNextButtonClicked parameter you are using, and if you are, you need to have opening and closing parentheses with onNextButtonClicked. so like this:

onClick = onNextButtonClicked

or

onClick = { onNextButtonClicked() }

**Comment by AAB999** [comment]
@brendanbdev
😊
Exactly this was the problem! I figured it out, as I tried to build the app in unit 4. There were curly braces for an empty Lambda on 2 "onNextButtonClicked" events, i had missed in following the instructions. So nothing happend :-)..In my CityApp, I got it right and the navigation is functional as it should. Thanks for the further instructions!
