### ISSUE TITLE
Test the Cupcake app: Android Basics in Compose

### ISSUE THREAD

**Issue by sandstroms** [google-developer-training/basic-android-kotlin-compose-training-cupcake#4]
The starter code (on "navigation" branch) does not include the ComposeRuleExtensions.kt file. This file contains the extension function `onNodeWithStringId(...)` which is needed for part 5 of this codelab.

**Comment by osuleymanova** [comment]
@sandstroms 
Please provide the URL of the codelab or GitHub repo at least.

**Comment by sandstroms** [comment]
Codelab URL: https://developer.android.com/codelabs/basic-android-kotlin-compose-test-cupcake?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-4-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-test-cupcake#4

GitHub repo URL: https://github.com/google-developer-training/basic-android-kotlin-compose-training-cupcake

To give a little more information, `ComposeRuleExtensions.kt` is on the "main" branch, but is not on the "navigation" branch. You can find it on the main branch here: https://github.com/google-developer-training/basic-android-kotlin-compose-training-cupcake/blob/main/app/src/androidTest/java/com/example/cupcake/test/ComposeRuleExtensions.kt. This file should also be on the "navigation" branch since it is the starter code, and the user is not instructed to create a file named `ComposeRuleExtensions.kt`, nor define the function `onNodeWithStringId(...)` in the codelab.

**Comment by osuleymanova** [comment]
@sandstroms 
Thanks a lot for your prompt reply. Now on we'll investigate the issue.

**Comment by osuleymanova** [comment]
Hello @sandstroms,

After downloading the starter code (in the navigation branch), the user needs to follow the steps provided in he codelab. The codelab **has instructions** for adding that ComposeRuleExtensions.kt file and the onNodeWithStringId(...) extension function in the section 5:
https://developer.android.com/codelabs/basic-android-kotlin-compose-test-cupcake?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-4-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-test-cupcake#4

<img width="961" alt="Screen Shot 2022-11-28 at 1 05 36 PM" src="https://user-images.githubusercontent.com/86437155/204383862-56547077-17e1-478c-b109-02868ec61951.png">

If all the steps were performed correctly in the code in the navigation branch, the user will still find the file and the function in the solution code in the main branch.
