### ISSUE TITLE
Navigate between screens with Compose: Android Basics with Compose

### ISSUE THREAD

**Issue by Chrisroid** [google-developer-training/basic-android-kotlin-compose-training-cupcake#43]
![Capture](https://user-images.githubusercontent.com/56808916/231123694-7f0d2d98-8502-4ab5-9909-970216a8df25.PNG)
_**CurrentScreen.title**_ wasn't implemented well into the example code as shown above

**Comment by johnshea** [comment]
Hi @Chrisroid 

Thank you for bringing this item to our attention.

The screenshot you provided was most helpful for finding it quickly.

The lesson has been corrected and republished.

Hope you are enjoying the course.

Regards.
