### ISSUE TITLE
Navigate between screens with Compose: Android Basics with Compose

### ISSUE THREAD

**Issue by agentges** [google-developer-training/basic-android-kotlin-compose-training-cupcake#44]
Missed word in the code snippet.
In section  `7. Make the AppBar respond to navigation`
The text says: `4. Inside CupcakeAppBar, replace the hardcoded app name with the current screen's title by passing in currentScreen.title to the call to getResource() for the title parameter of TopAppBar.`
But the following code snippet lacks a call to the currentScreen.title:  `title = { Text(stringResource(currentScreen.)) },`

**Comment by johnshea** [comment]
Hi @agentges 

Thank you for bringing this item to our attention.

The lesson has been corrected and republished.

Hope you are enjoying the course.

Regards.
