### ISSUE TITLE
Navigate between screens with Compose: Android Basics with Compose

### ISSUE THREAD

**Issue by appsparkler** [google-developer-training/basic-android-kotlin-compose-training-cupcake#45]
Point number 4:

![image](https://user-images.githubusercontent.com/12084821/232253240-43a1cac3-5f44-462d-9022-69fe4d2e4d6d.png)

This could be `title = { Text(stringResource(currentScreen.title)) },` - notice that the `.title` is missing in the image.

**Comment by johnshea** [comment]
Hi @appsparkler 

Thank you for bringing this issue to our attention.

It has been corrected and republished.

Hope you are enjoying the course!

Regards.
