### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by Gamer2015** [google-developer-training/basic-android-kotlin-compose-training-cupcake#46]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-navigation

**In which task and step of the codelab can this issue be found?**
Task 7, Step 4

**Describe the problem**
The code for the title of the TopAppBar has a syntax error, it is missing the string "title" after 
```
TopAppBar(
   title = { Text(stringResource(currentScreen.
```

**Additional information**
<img width="1409" alt="Screenshot" src="https://user-images.githubusercontent.com/6293177/232223259-b12f9e9c-d74d-405e-bedd-f58d116fc48b.png">

**Comment by johnshea** [comment]
Hi @Gamer2015 

Thank you for bringing this item to our attention.

The lesson has been corrected and republished.

Hope you are enjoying the course.

Regards.
