### ISSUE TITLE
Could not find androidx.compose.ui:ui-test-junit4:. Required by:     project :app

### ISSUE THREAD

**Issue by machado001** [google-developer-training/basic-android-kotlin-compose-training-cupcake#47]
**URL of codelab**
[Basic android-kotlin-compose-training (Test the Cupcake App) ](https://developer.android.com/codelabs/basic-android-kotlin-compose-test-cupcake?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-4-pathway-2%3Fhl%3Dpt-br%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-test-cupcake#6)

**In which task and step of the codelab can this issue be found?**
[Get the solution code (cupcake) ](https://developer.android.com/codelabs/basic-android-kotlin-compose-test-cupcake?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-4-pathway-2%3Fhl%3Dpt-br%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-test-cupcake#6)

**Describe the problem**
After get the solution code and run tests from `androidTest>java.com.example.cupcake.test>CupcakeScreenNavigationTest` and run tests from class CupcakeScreenNavigationTest { ... } , you will receive the error 
`Could not find androidx.compose.ui:ui-test-junit4:.
Required by:
    project :app`

**Steps to reproduce?**
1. Go to `androidTest>java.com.example.cupcake.test>CupcakeScreenNavigationTest`
![Screenshot from 2023-04-17 02-20-15](https://user-images.githubusercontent.com/101916850/232386527-148c230a-1df5-4073-9e3b-1a45ed1543d7.png)

3. Click on `Run CupcakeScreenNavigationTest` in class `CupcakeScreenNavigationTest` at line 37.
![Screenshot from 2023-04-17 02-25-52](https://user-images.githubusercontent.com/101916850/232388241-1f25d3eb-64f0-4bc2-87ce-8587a4d229ec.png)

5. See error  ```Could not find androidx.compose.ui:ui-test-junit4:.
Required by:
    project :app```

**Versions**
_Android Studio version: Android Studio Eletric Eel | 2022.1.1 Patch 2
_API version of the emulator: 33

**Additional information**
In build.gradle, we have already an  **androidTestImplementation "androidx.compose.ui:ui-test-junit4"**, as shown below:
![Screenshot from 2023-04-17 02-28-41](https://user-images.githubusercontent.com/101916850/232388906-475dede2-ba80-4673-b07e-ccbe0ce41d7a.png)

**Comment by Raygrantham51** [comment]
1WhoGivesaFuck!

**Comment by Raygrantham51** [comment]
I've shared an item with you:

Intellectual_Property-Proactive-2020_H2
https://docs.google.com/spreadsheets/d/16ToxTOGkex3YlR9-boNjFAtfKSMrWpoPurnvdf5vMIk/edit?usp=sharing&invite=CPeQ2oAL&ts=64415a67

It's not an attachment -- it's stored online. To open this item, just click  
the link above.

**Comment by AuYahyire** [comment]
I am facing the same issue, with clean downloaded code from GitHub, without any modification from my side.

**Comment by machado001** [comment]
Thank you boys, @DeanH1990 and @AuYahyire. I will close it now.
