### ISSUE TITLE
Navigate between screens with Compose: Android Basics with Compose

### ISSUE THREAD

**Issue by deep2k4** [google-developer-training/basic-android-kotlin-compose-training-cupcake#52]
Following along, half way through adding button handlers to the OrderSummaryScreen, it states:

"Add another parameter of type (String, String) -> Unit with a default value of {} and name this one onSendButtonClicked."
and shows:

@Composable
fun OrderSummaryScreen(
    orderUiState: OrderUiState,
    onCancelButtonClicked: () -> Unit = {},
    onSendButtonClicked: (String, String) -> Unit = {},
    modifier: Modifier = Modifier
){
    ...
}

But that onSendButtonClicked wont compile correctly in the end. Besides it breaks the former @Preview, which is also nowhere mentioned in the Tutorial. You should fix that.

**Comment by johnshea** [comment]
Hi @deep2k4 

Thank you for reporting this issue.

The lesson is being updated to address it and will be republished in the near future.

Hope you are enjoying the course!

Regards.
