### ISSUE TITLE
Navigate between screens with Compose: Android Basics with Compose

### ISSUE THREAD

**Issue by KostyaBara** [google-developer-training/basic-android-kotlin-compose-training-cupcake#53]
Unit 4. Pathway 1. 
4. Define routes and create a NavHostController
You'll call the composable() function once for each of the four routes.
...
7. The flavor screen gets the list of flavors from the app's string resources. Transform the list...
Please, check brackets after code snippet in this part.

**Comment by johnshea** [comment]
Hi @KostyaBara 

Thank you for bringing this our attention.

It is being corrected and the fix will be published in the near future.

Hope you are enjoying the course!

Regards.
