### ISSUE TITLE
Navigate between screens with Compose: Android Basics with Compose

### ISSUE THREAD

**Issue by Arthur-Milchior** [google-developer-training/basic-android-kotlin-compose-training-cupcake#54]
In page 2 https://developer.android.com/codelabs/basic-android-kotlin-compose-navigation?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-4-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-navigation#1 
Usually you give a link to github. You forgot, in this codelab, to add a direct link

**Comment by johnshea** [comment]
Hi @Arthur-Milchior 

Thank you for reporting this issue.

The lesson has been updated with a direct link to GitHub as expected and will be republished in the near future.

Hope you are enjoying the course!

Regards.
