### ISSUE TITLE
Navigate between screens with Compose: Android Basics with Compose

### ISSUE THREAD

**Issue by cmd770** [google-developer-training/basic-android-kotlin-compose-training-cupcake#55]
In the following code snippet (which is found in task [4. Define routes and create a NavHostController](https://developer.android.com/codelabs/basic-android-kotlin-compose-navigation#3)),
the line 8 should not have curly braces:
```
import com.example.cupcake.ui.SelectOptionScreen

composable(route = CupcakeScreen.Flavor.name) {
    val context = LocalContext.current
    SelectOptionScreen(
        subtotal = uiState.price,
        options = DataSource.flavors.map { id -> context.resources.getString(id) }
        }
    )
}
```
Instead, it should look like this:
```
import com.example.cupcake.ui.SelectOptionScreen

composable(route = CupcakeScreen.Flavor.name) {
    val context = LocalContext.current
    SelectOptionScreen(
        subtotal = uiState.price,
        options = DataSource.flavors.map { id -> context.resources.getString(id) }
    )
}
```

**Comment by johnshea** [comment]
Hi @cmd770 

Thank you for bringing this issue to our attention.

It has been corrected and the lesson will be republished in the near future with the fix.

Hope you are enjoying the course!

Regards.
