### ISSUE TITLE
Navigate between screens with Compose: Android Basics with Compose

### ISSUE THREAD

**Issue by Canapeclic** [google-developer-training/basic-android-kotlin-compose-training-cupcake#60]
I was reading the tutorial on developping mobile application and I think some examples are missing here (french version) :

Spécifiez le type de données supplémentaires envoyées avec l'intent. Vous pouvez utiliser "text/plain" pour un texte simple, mais d'autres types, tels que <insert examples>, sont également disponibles.

This is located in Navigate between screens with Compose: Android Basics with Compose -> Navigate to another app.

I checked the english version and it seems to be fine so I don't know if french is the only language affected by this issue.

**Comment by johnshea** [comment]
Hi @Canapeclic 

Thank you for bringing this to our attention.

It has been corrected and the updated lesson will be republished shortly.

Hope you are enjoying the course!

Regards.
