### ISSUE TITLE
Navigate between screens with Compose: Android Basics with Compose

### ISSUE THREAD

**Issue by irritated-student** [google-developer-training/basic-android-kotlin-compose-training-cupcake#61]
The Starter Code for this training exercise does not produce the result offered with the solution code. It's really annoying.  The solution code works, but it cannot be achieved using the starter code  plus instructions..  During the fifth part of the exercise the error the difference between the instruction and the solution is very obvious,  Thands for nothing regarding the coding exercise with no matching solution.

**Comment by johnshea** [comment]
Hi @irritated-student 

Sorry to learn that the instructions provided are not sufficient.

If you could provide additional details and screenshots as to what is causing you issue, we would be able to investigate and correct as needed in a more efficient manner.

I look forward to your response.

Regards.

**Comment by irritated-student** [comment]
Let's just start here.  Below is a link to quadrant exercise  which
provides a git hub solution that requires use of a compose function named
ComposeInfoCard   which requires parameters which will not work with the a
regular.Compose Card.  Since a Google search will not render one word
regarding ComposeInfoCard shoved in there in any form AND the term
ComposeInfoCard was not popping up in any of the literature I can find, I
ask you, how would a student be able to successfully complete the exercise
with the solution provided in the link to github. I figured how to do it
with a regular Card, columns, boxes etc , but it is not for the faint of
heart for somebody trying to learn Compose and find a solution on their own
as encouraged and indicated.  Please direct me to a place where I would
know about the ComposeInfoCard by the time I reached that point in your
tutorial, or ever know about it, for that matter.   The link to the github
solution is in the exercise below for the section to use a quadrant.  I
never thought I would hear a peep, so thanks for asking.

https://developer.android.com/codelabs/basic-android-kotlin-compose-composables-practice-problems?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-composables-practice-problems#3

**Comment by irritated-student** [comment]
I did  send you an email with a link and an example.  I hope you get a
chance to look at the situation and respond. I won't bug you again.

**Comment by johnshea** [comment]
Hi @irritated-student 

Thank you for your follow up with the additional details.

I will be pass it to the appropriate team for further consideration on ways this can be addressed to help future students.

I hope you are still enjoying the course!

Regards.
