### ISSUE TITLE
Test the Cupcake app: Android Basics with Compose

### ISSUE THREAD

**Issue by SudheerRajV** [google-developer-training/basic-android-kotlin-compose-training-cupcake#63]
In this [page](https://developer.android.com/codelabs/basic-android-kotlin-compose-test-cupcake?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-4-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-test-cupcake#4) under **Maximize test coverage** section please remove dot(.) in front of navController under **cupcakeNavHost_clickCancelOnFlavorScreen_navigatesToStartOrderScreen** function.

**Comment by johnshea** [comment]
Hi @SudheerRajV.

Thank you for pointing out this issue.

It has been corrected and the updated lesson will be published in the near future.

Hope you are enjoying the course.

Regards.
