### ISSUE TITLE
Test the Cupcake app: Android Basics in Compose

### ISSUE THREAD

**Issue by mikef-dk** [google-developer-training/basic-android-kotlin-compose-training-cupcake#7]
## Issue 1

The third snippet is kinda misleading
```kt
@Test
fun cupcakeNavHost_verifyStartDestination() {assertEquals(Cupcake.Start.name, currentBackStackEntry?.destination?.route)
}
```
`Cupcake.Start.name` should be `CupcakeScreen.Start.name`. Additionally `currentBackStackEntry` cannot be resolved - it should read `navController.currentBackStackEntry?.destination?.route`.

To sum it up:
```
@Test
fun cupcakeNavHost_verifyStartDestination() {
    assertEquals(CupcakeScreen.Start.name, navController.currentBackStackEntry?.destination?.route)
}
```

---

## Issue 2

Following the *Verify navigation to the Flavor screen* section the code snippet reads
```
@Test
fun cupcakeNavHost_clickOneCupcake_navigatesToSelectFlavorScreen() {
   composeTestRule.onNodeWithStringId(R.string.one_cupcake)
       .performClick()
}
```
However there is no `#onNodeWithStringId` in `androidx.compose.ui.test` - see [docs](https://developer.android.com/reference/kotlin/androidx/compose/ui/test/package-summary#(androidx.compose.ui.test.SemanticsNodeInteractionsProvider).onNodeWithContentDescription(kotlin.String,kotlin.Boolean,kotlin.Boolean,kotlin.Boolean))
By looking at the [solution](https://github.com/google-developer-training/basic-android-kotlin-compose-training-cupcake/blob/main/app/src/androidTest/java/com/example/cupcake/test/ComposeRuleExtensions.kt) it becomes clear that this is an extension method that was added however it is not mentioned on the Codelab.

**Comment by kofi-k** [comment]
Oh, i see you got ahead of me reporting this one and that be cool

**Comment by johnshea** [comment]
Hi @mikef-dk @kofi-k 

Thank you for reporting these issues.

The corrections have been made and the updated lesson republished.

Hope you are enjoying the course!

Regards.
