### ISSUE TITLE
Navigate between screens with Compose: Android Basics with Compose

### ISSUE THREAD

**Issue by Maxmarra** [google-developer-training/basic-android-kotlin-compose-training-cupcake#8]
**Note**: The quantityOptions property comes from calling collectAsState() in the line before the NavHost. Other properties from the view model will be accessed the same way.

It looks like it does not
It comes from DataSource.kt 
**quantityOptions**  has nothing to do with the viewmodel

**Comment by osuleymanova** [comment]
Hello @Maxmarra,

Thank you for reaching out to us and sharing your feedback. The text is updated by the Note message in the codelab:

![Screenshot 2023-01-09 at 11 35 27 AM](https://user-images.githubusercontent.com/86437155/211394640-78dfecfd-9fee-4b3a-980e-62ec446cbac5.png)
